name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AIRFLOW_IMAGE: airflow-custom
      TRINO_IMAGE: trino-custom
      AIRFLOW_PORT: ${{ secrets.AIRFLOW_PORT }}
      AIRFLOW_EXECUTOR: ${{ secrets.AIRFLOW_EXECUTOR }}
      AIRFLOW_DB: ${{ secrets.AIRFLOW_DB }}
      AIRFLOW_SECRET: ${{ secrets.AIRFLOW_SECRET }}
      AIRFLOW_USER: ${{ secrets.AIRFLOW_USER }}
      AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}
      AIRFLOW_FIRSTNAME: ${{ secrets.AIRFLOW_FIRSTNAME }}
      AIRFLOW_LASTNAME: ${{ secrets.AIRFLOW_LASTNAME }}
      AIRFLOW_ROLE: ${{ secrets.AIRFLOW_ROLE }}
      AIRFLOW_EMAIL: ${{ secrets.AIRFLOW_EMAIL }}
      TRINO_PORT: ${{ secrets.TRINO_PORT }}
      TRINO_CATALOG_PATH: ${{ secrets.TRINO_CATALOG_PATH }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      AIRFLOW_METRICS_PORT: ${{ secrets.AIRFLOW_METRICS_PORT }}
      NODE_EXPORTER_PORT: ${{ secrets.NODE_EXPORTER_PORT }}
      PROMETHEUS_PORT: ${{ secrets.PROMETHEUS_PORT }}
      GRAFANA_PORT: ${{ secrets.GRAFANA_PORT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check formatting with Black (non-blocking)
      continue-on-error: true
      run: |
        pip install black
        black docker/

    - name: Format YAML with Prettier (non-blocking)
      continue-on-error: true
      run: |
        npm install --global prettier
        prettier --write "**/*.{yml,yaml}"

    - name: Install Docker Compose CLI plugin
      run: |
        mkdir -p ~/.docker/cli-plugins/
        curl -SL https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
        chmod +x ~/.docker/cli-plugins/docker-compose
        docker compose version

    - name: Build Docker images via Compose
      run: docker compose build

    - name: Deploy files to remote host
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: "."
        target: "~/stack_data"

    - name: Create .env on remote server
      uses: appleboy/ssh-action@master
      env:
        AIRFLOW_USER: ${{ secrets.AIRFLOW_USER }}
        AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}
        AIRFLOW_DB: ${{ secrets.AIRFLOW_DB }}
        AIRFLOW_SECRET: ${{ secrets.AIRFLOW_SECRET }}
        AIRFLOW_PORT: ${{ secrets.AIRFLOW_PORT }}
        AIRFLOW_EXECUTOR: ${{ secrets.AIRFLOW_EXECUTOR }}
        AIRFLOW_FIRSTNAME: ${{ secrets.AIRFLOW_FIRSTNAME }}
        AIRFLOW_LASTNAME: ${{ secrets.AIRFLOW_LASTNAME }}
        AIRFLOW_ROLE: ${{ secrets.AIRFLOW_ROLE }}
        AIRFLOW_EMAIL: ${{ secrets.AIRFLOW_EMAIL }}
        TRINO_PORT: ${{ secrets.TRINO_PORT }}
        TRINO_CATALOG_PATH: ${{ secrets.TRINO_CATALOG_PATH }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        AIRFLOW_METRICS_PORT: ${{ secrets.AIRFLOW_METRICS_PORT }}
        NODE_EXPORTER_PORT: ${{ secrets.NODE_EXPORTER_PORT }}
        PROMETHEUS_PORT: ${{ secrets.PROMETHEUS_PORT }}
        GRAFANA_PORT: ${{ secrets.GRAFANA_PORT }}
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd ~/stack_data
          cat > .env <<EOF
          AIRFLOW_USER=$AIRFLOW_USER
          AIRFLOW_PASSWORD=$AIRFLOW_PASSWORD
          AIRFLOW_DB=$AIRFLOW_DB
          AIRFLOW_SECRET=$AIRFLOW_SECRET
          AIRFLOW_PORT=$AIRFLOW_PORT
          AIRFLOW_EXECUTOR=$AIRFLOW_EXECUTOR
          AIRFLOW_FIRSTNAME=$AIRFLOW_FIRSTNAME
          AIRFLOW_LASTNAME=$AIRFLOW_LASTNAME
          AIRFLOW_ROLE=$AIRFLOW_ROLE
          AIRFLOW_EMAIL=$AIRFLOW_EMAIL
          TRINO_PORT=$TRINO_PORT
          TRINO_CATALOG_PATH=$TRINO_CATALOG_PATH
          POSTGRES_USER=$POSTGRES_USER
          POSTGRES_PASSWORD=$POSTGRES_PASSWORD
          POSTGRES_DB=$POSTGRES_DB
          POSTGRES_PORT=$POSTGRES_PORT
          AIRFLOW_METRICS_PORT=$AIRFLOW_METRICS_PORT
          NODE_EXPORTER_PORT=$NODE_EXPORTER_PORT
          PROMETHEUS_PORT=$PROMETHEUS_PORT
          GRAFANA_PORT=$GRAFANA_PORT
          EOF

    - name: Deploy containers with podman-compose
      uses: appleboy/ssh-action@master
      env:
        AIRFLOW_USER: ${{ secrets.AIRFLOW_USER }}
        AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}
        AIRFLOW_DB: ${{ secrets.AIRFLOW_DB }}
        AIRFLOW_SECRET: ${{ secrets.AIRFLOW_SECRET }}
        AIRFLOW_PORT: ${{ secrets.AIRFLOW_PORT }}
        AIRFLOW_EXECUTOR: ${{ secrets.AIRFLOW_EXECUTOR }}
        AIRFLOW_FIRSTNAME: ${{ secrets.AIRFLOW_FIRSTNAME }}
        AIRFLOW_LASTNAME: ${{ secrets.AIRFLOW_LASTNAME }}
        AIRFLOW_ROLE: ${{ secrets.AIRFLOW_ROLE }}
        AIRFLOW_EMAIL: ${{ secrets.AIRFLOW_EMAIL }}
        TRINO_PORT: ${{ secrets.TRINO_PORT }}
        TRINO_CATALOG_PATH: ${{ secrets.TRINO_CATALOG_PATH }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        AIRFLOW_METRICS_PORT: ${{ secrets.AIRFLOW_METRICS_PORT }}
        NODE_EXPORTER_PORT: ${{ secrets.NODE_EXPORTER_PORT }}
        PROMETHEUS_PORT: ${{ secrets.PROMETHEUS_PORT }}
        GRAFANA_PORT: ${{ secrets.GRAFANA_PORT }}
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd ~/stack_data
          podman-compose down
          podman-compose --env-file .env up -d --build
