name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AIRFLOW_IMAGE: airflow-custom
      TRINO_IMAGE: trino-custom

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Lint Python
      run: |
        pip install flake8
        flake8 docker/

    - name: Lint YAML
      run: |
        sudo apt install yamllint -y
        yamllint .

    - name: Build Docker images
      run: |
        docker build -t $AIRFLOW_IMAGE ./docker/airflow
        docker build -t $TRINO_IMAGE ./docker/trino

    - name: Deploy via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        source: "."
        target: "~/stack_data"

    - name: Remote deploy command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd ~/stack_data
          docker compose down
          docker compose up -d --build
